### ISSUE TITLE
Swagger file gen

### ISSUE THREAD

**Issue by gedw99** [pydio/cells-sdk-go#1]
I am trying to work out how to match the rest gateway and the services in terms of when I change a service and then needing to update the swagger file.

Are you code generating the swagger file or hand editting it ?

**Comment by cdujeu** [comment]
hi, it's generated - please give us a couple of days, we are working on the developer doc :-)

**Comment by gedw99** [comment]
@cdujeu Nice. Super impressive architecture.

Really think this is cool.

**Comment by gedw99** [comment]
@cdujeu 
Can i ask for a few quick things here.
I noticed you have PHP and Python. for some other layers. 
they seem ripe for converting to golang 

Suggestions:
Replace Elastic with BLeve
Replace PHP with gobuffalo

I use the ones i suggested and its fast and easy

**Comment by cdujeu** [comment]
hi, what you see are the previous version layers. 
To summarize : 
- Pydio 8 = Monolithic LAMP stack
- Pydio Cells = Go + Thin PHP Layer [removing this php fully is in progress]
And in Pydio Cells the search engine is already using Bleve ;-)
