### ISSUE TITLE
Presigning a PutObjectRequest and then trying to send it always fails

### ISSUE THREAD

**Issue by IanPhilips** [pydio/cells-sdk-go#3]
Ubuntu, Cells v1.2.1
Using this input:

	

` var input = (&s3.PutObjectInput{}).SetBucket("io").SetKey("personal-files"+ "/" + pathToFile))`

the following code works:
`resp, _ := svc.PutObjectRequest(input.SetBody(strings.NewReader("hi"))`
` err = resp.Send()`

yet the following :

	
` resp, _ := svc.PutObjectRequest(input)`
` urlStr, err := resp.Presign(15 * time.Minute)`
` 	if err != nil {`
` 		fmt.Println("error presigning request", err)`
` 		return }`
` 	req, err := http.NewRequest("PUT", urlStr, strings.NewReader("hi")))`
`         defClient, err := http.DefaultClient.Do(req)`
` 	fmt.Println(defClient, err)`

always returns the error: "Unable to save an object /io/personal-files/test.txt" cause="{\"id\":\"pydio.lib.views\",\"code\":404,\"detail\":\"Workspace not found in Path\"

Any idea why that is?

**Comment by IanPhilips** [comment]
It looks like presigning the `GetObjectRequest` doesn't work either, so it seems like the problem is at the `Presign` operation

**Comment by cdujeu** [comment]
Hi Ian,
What do you use for auth? 
Try using apikey "gateway" / api secret "gatewaysecret" (yes, these values), and appending the JWT as a query parameter to the presigned URL, with pydio_jwt=JWT_VALUE.
(We strip this before checking the URL signature, so it will not interfere.)
Charles

**Comment by IanPhilips** [comment]
adding the pydio_jwt fixed it! Thank you very much!

**Comment by IanPhilips** [comment]
I'm curious why I have to set that as when I call config2.GetPreparedS3CLient, it calls `	jwt, err := retrieveToken(sdkConfig)`

**Comment by cdujeu** [comment]
It's just specific to presigned and how the signature is checked server side - but indeed, maybe we should wrap some calls to make this directly with the jwt.

**Comment by cdujeu** [comment]
the good news is that we use presigned here and there in the front, so it's not a poor-boy feature for us :-)

**Comment by IanPhilips** [comment]
Thanks for the info, Charles. You can leave this open as a feature request or close it, whatever you prefer.

**Comment by IanPhilips** [comment]
Another question for you, when I make that signed put request, shouldn't the server respond with something other thatn a status code? Ideally it'd return the UUID to create a sharing link.

**Comment by cdujeu** [comment]
Closing this one :-)
